# Generated by Django 5.2.17 on 2026-10-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma')], max_length=2)),
                ('unit_price_cents', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('is_scale_product', models.BooleanField(default=False)),
                ('is_quick_access', models.BooleanField(default=False)),
                ('appears_on_order_slip', models.BooleanField(default=False)),
                ('quick_access_order', models.PositiveIntegerField(default=0)),
                ('slip_order', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['quick_access_order', 'description', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit__in', ['UN', 'KG'])), name='product_valid_unit'), models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='product_description_not_empty'), models.CheckConstraint(condition=models.Q(('unit_price_cents__lte', 9000000000000)), name='product_price_limit'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='product_positive_revision'), models.CheckConstraint(condition=models.Q(('is_scale_product', False), models.Q(('active', True), ('unit', 'KG')), _connector='OR'), name='scale_product_active_kg'), models.UniqueConstraint(condition=models.Q(('is_scale_product', True)), fields=('is_scale_product',), name='one_scale_product')],
            },
        ),
    ]
