# Generated by Django 5.2.17 on 2026-10-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('request_key', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Aberta'), ('FINALIZED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 2147483647)), name='order_number_limits'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('finalized_at__isnull', True), ('status', 'DRAFT')), models.Q(('cancelled_at__isnull', False), ('finalized_at__isnull', True), ('status', 'CANCELLED')), models.Q(('cancelled_at__isnull', True), ('finalized_at__isnull', False), ('status', 'FINALIZED')), _connector='OR'), name='order_status_dates_consistent')],
            },
        ),
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='order_sequence_singleton'), models.CheckConstraint(condition=models.Q(('next_number__gte', 1)), name='order_sequence_positive')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SCALE', 'Balança')], max_length=6)),
                ('product_description', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=2)),
                ('quantity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price_cents', models.PositiveBigIntegerField()),
                ('total_cents', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_links', to='measurements.measurement')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True), ('measurement__isnull', False)), fields=('measurement',), name='one_active_item_per_measurement'), models.CheckConstraint(condition=models.Q(models.Q(('quantity_units__gte', 1), ('quantity_units__isnull', False), ('quantity_units__lte', 100000), ('unit', 'UN'), ('weight_grams__isnull', True)), models.Q(('quantity_units__isnull', True), ('unit', 'KG'), ('weight_grams__gte', 1), ('weight_grams__isnull', False), ('weight_grams__lte', 1000000)), _connector='OR'), name='item_quantity_matches_unit'), models.CheckConstraint(condition=models.Q(models.Q(('measurement__isnull', True), ('source', 'MANUAL')), models.Q(('measurement__isnull', False), ('source', 'SCALE'), ('unit', 'KG')), _connector='OR'), name='item_source_matches_measurement'), models.CheckConstraint(condition=models.Q(('total_cents__lte', 9000000000000), ('unit_price_cents__lte', 9000000000000)), name='item_money_limits'), models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('removed_at__isnull', True)), models.Q(('active', False), ('removed_at__isnull', False)), _connector='OR'), name='item_removal_consistent')],
            },
        ),
    ]
