# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(default='', max_length=120)),
                ('footer', models.TextField(default='', max_length=500)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='document_configuration_singleton'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='document_configuration_revision')],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('kind', models.CharField(choices=[('INITIAL', 'Primeira via'), ('REPRINT', 'Segunda via')], max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando simulação'), ('SUBMITTING', 'Simulação em andamento'), ('SIMULATED', 'Simulada — sem impressão física'), ('FAILED', 'Falha confirmada'), ('UNKNOWN', 'Resultado incerto — revise antes de reimprimir')], default='PENDING', max_length=10)),
                ('attempt_key', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('result_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='printing.orderdocument')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'INITIAL')), fields=('document',), name='one_initial_job_per_document'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'SUBMITTING'])), fields=('document',), name='one_pending_job_per_document'), models.CheckConstraint(condition=models.Q(('kind__in', ['INITIAL', 'REPRINT'])), name='print_job_valid_kind'), models.CheckConstraint(condition=models.Q(models.Q(('attempt_key__isnull', True), ('attempts', 0), ('completed_at__isnull', True), ('status', 'PENDING'), ('submitted_at__isnull', True)), models.Q(('attempt_key__isnull', False), ('attempts__gte', 1), ('completed_at__isnull', True), ('status', 'SUBMITTING'), ('submitted_at__isnull', False)), models.Q(('attempt_key__isnull', False), ('attempts__gte', 1), ('completed_at__isnull', False), ('status__in', ['SIMULATED', 'FAILED', 'UNKNOWN']), ('submitted_at__isnull', False)), _connector='OR'), name='print_job_state_consistent')],
            },
        ),
    ]
