# Generated by Django 5.2.17 on 2026-10-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='printjob',
            name='print_job_state_consistent',
        ),
        migrations.AddField(
            model_name='printjob',
            name='delivery_mode',
            field=models.CharField(choices=[('PREVIEW', 'Simulação'), ('RAW', 'Impressão física')], default='PREVIEW', max_length=7),
        ),
        migrations.AddField(
            model_name='printjob',
            name='printer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='printjob',
            name='spooler_job_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando envio'), ('SUBMITTING', 'Envio em andamento'), ('SIMULATED', 'Simulada — sem impressão física'), ('SPOOL_ACCEPTED', 'Aceita pelo spooler — confira o papel'), ('FAILED', 'Falha confirmada'), ('UNKNOWN', 'Resultado incerto — revise antes de reimprimir')], default='PENDING', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_mode', 'PREVIEW'), ('printer_name', '')), models.Q(('delivery_mode', 'RAW'), models.Q(('printer_name', ''), _negated=True)), _connector='OR'), name='print_job_transport_consistent'),
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_mode', 'RAW'), ('spooler_job_id__isnull', False), ('status', 'SPOOL_ACCEPTED')), models.Q(models.Q(('status', 'SPOOL_ACCEPTED'), _negated=True), ('spooler_job_id__isnull', True)), _connector='OR'), name='print_job_spooler_consistent'),
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt_key__isnull', True), ('attempts', 0), ('completed_at__isnull', True), ('status', 'PENDING'), ('submitted_at__isnull', True)), models.Q(('attempt_key__isnull', False), ('attempts__gte', 1), ('completed_at__isnull', True), ('status', 'SUBMITTING'), ('submitted_at__isnull', False)), models.Q(('attempt_key__isnull', False), ('attempts__gte', 1), ('completed_at__isnull', False), ('status__in', ['SIMULATED', 'SPOOL_ACCEPTED', 'FAILED', 'UNKNOWN']), ('submitted_at__isnull', False)), _connector='OR'), name='print_job_state_consistent'),
        ),
    ]
