# Generated by Django 5.2.17 on 2026-10-04 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('printing', '0002_remove_printjob_print_job_state_consistent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdocument',
            name='is_final',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='orderdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('order',), name='one_final_document_per_order'),
        ),
    ]
