# Generated by Django 5.2.17 on 2026-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_orderdocument_is_final_alter_orderdocument_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentconfiguration',
            name='logo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
