# Generated by Django 5.2.17 on 2026-10-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('scale_port', models.CharField(default='COM3', max_length=8)),
                ('printer_name', models.CharField(default='balanca', max_length=120)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='hardware_configuration_singleton'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='hardware_configuration_revision')],
            },
        ),
    ]
