# Generated by Django 5.2.17 on 2026-10-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Restaurante Local', max_length=80)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='application_configuration_singleton'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='application_configuration_revision'), models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='application_configuration_name_nonempty')],
            },
        ),
    ]
