# Generated by Django 5.2.17 on 2026-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_applicationconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareconfiguration',
            name='scale_protocol',
            field=models.CharField(choices=[('USECB2', 'USECB2 — peso líquido e tara'), ('PROT_F', 'PROT F — peso com sinal e instabilidade')], default='USECB2', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='hardwareconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('scale_protocol__in', ['USECB2', 'PROT_F'])), name='hardware_configuration_protocol'),
        ),
    ]
