# Generated by Django 5.2.17 on 2026-10-03 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('capture_key', models.UUIDField(unique=True)),
                ('product_description', models.CharField(max_length=120)),
                ('unit_price_cents', models.PositiveBigIntegerField()),
                ('total_cents', models.PositiveBigIntegerField()),
                ('net_weight_grams', models.PositiveIntegerField()),
                ('tare_grams', models.PositiveIntegerField(default=0)),
                ('device', models.CharField(max_length=120)),
                ('stability_parameters', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('USED', 'Utilizada'), ('DISCARDED', 'Descartada')], default='AVAILABLE', max_length=10)),
                ('discard_reason', models.CharField(blank=True, max_length=30)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'USED', 'DISCARDED'])), name='measurement_valid_status'), models.CheckConstraint(condition=models.Q(('net_weight_grams__gte', 1), ('net_weight_grams__lte', 1000000)), name='measurement_weight_limits'), models.CheckConstraint(condition=models.Q(('total_cents__lte', 9000000000000), ('unit_price_cents__lte', 9000000000000)), name='measurement_money_limits'), models.CheckConstraint(condition=models.Q(models.Q(('discard_reason', 'MANUAL_DISCARD'), ('discarded_at__isnull', False), ('status', 'DISCARDED')), models.Q(models.Q(('status', 'DISCARDED'), _negated=True), ('discard_reason', ''), ('discarded_at__isnull', True)), _connector='OR'), name='measurement_discard_consistent')],
            },
        ),
    ]
