# Generated by Django 5.2.17 on 2026-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='tare_grams',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
